### ISSUE TITLE
Snapshot giving timeout error

### ISSUE THREAD

**Issue by newlund** [home-assistant/supervisor#2412]
Hi,

I have an automated full snapshot job every night. For a long time I get these errors every night:

2021-01-08 01:05:00 ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /snapshots/new/full request
2021-01-08 01:05:00 ERROR (MainThread) [homeassistant.components.hassio] Error on Hass.io API: 

It seems the timeout is 5 min because the job starts at 01:00?

Previously I had a quite large influx db causing the snapshot size to be 600-800MB. It took approx. 20-30 min to do a full snapshot.

Now I have cleared the influx db and the snapshots are now between 150-160MB. A couple of nights I did not get the warning but now they have started to appear again. The latest snapshot is 157.7MB.

However, despite the warning, the snapshots seems to work ok.

Can the timeout be extended to 1h? Or perhaps make it user configurable?

I'm running the latest release as of today.

Version | 2021.1.0
Installation Type | Home Assistant OS

Thanks!
Nicklas Nylund

**Comment by ludeeus** [comment]
Fixed by <https://github.com/home-assistant/supervisor/pull/2439>

**Comment by newlund** [comment]
👍😊

**Comment by newlund** [comment]
I'm still getting this error with v2021.3.4

Logger: homeassistant.components.hassio.handler
Source: components/hassio/handler.py:206
Integration: Hass.io (documentation, issues)
First occurred: 1:05:00 (1 occurrences)
Last logged: 1:05:00

Timeout on /snapshots/new/full request

**Comment by r0b3rt74** [comment]
Same here:

Logger: homeassistant.components.hassio.handler
Source: components/hassio/handler.py:206
Integration: Hass.io (documentation, issues)
First occurred: 18:42:45 (4 occurrences)
Last logged: 19:40:07

Timeout on /snapshots/new/full request
Timeout on /snapshots/new/partial request

**Comment by croister** [comment]
Same here though I started the snapshot manually through the UI.

Home Assistant OS 5.12
Supervisor Version: supervisor-2021.03.6
Core Version: core-2021.3.4

I have a home-assistant_v2.db that is over 700 MB which is probably why it is taking a long time to create the snapshot.

From Supervisor log (time in UTC):
>21-04-01 00:58:57 INFO (MainThread) [supervisor.snapshots] Creating new full-snapshot with slug &lt;slug&gt;
>21-04-01 00:58:57 INFO (MainThread) [supervisor.snapshots] Snapshotting &lt;slug&gt; store Add-ons
>...
> &lt;some successful addon snapshots&gt;
>...
>21-04-01 00:58:58 INFO (MainThread) [supervisor.snapshots] Snapshotting &lt;slug&gt; store folders
>21-04-01 00:58:58 INFO (SyncWorker_5) [supervisor.snapshots.snapshot] Snapshot folder share
>21-04-01 00:58:58 INFO (SyncWorker_5) [supervisor.snapshots.snapshot] Snapshot folder share done
>21-04-01 00:58:58 INFO (SyncWorker_4) [supervisor.snapshots.snapshot] Snapshot folder media
>21-04-01 00:58:58 INFO (SyncWorker_4) [supervisor.snapshots.snapshot] Snapshot folder media done
>21-04-01 00:58:58 INFO (SyncWorker_6) [supervisor.snapshots.snapshot] Snapshot folder addons/local
>21-04-01 00:58:58 INFO (SyncWorker_6) [supervisor.snapshots.snapshot] Snapshot folder addons/local done
>21-04-01 00:58:58 INFO (SyncWorker_0) [supervisor.snapshots.snapshot] Snapshot folder homeassistant

From Core log (time in Swedish summer time = UTC+2 => 5 min later):
>2021-04-01 03:03:57 ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /snapshots/new/full request
>2021-04-01 03:03:57 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /snapshots/new/full - 

The UI gave the feedback that the snapshot failed but after a few more minutes is completed anyway in the background.

From Supervisor log (time in UTC):
>21-04-01 01:08:44 INFO (SyncWorker_0) [supervisor.snapshots.snapshot] Snapshot folder homeassistant done
>21-04-01 01:08:44 INFO (SyncWorker_3) [supervisor.snapshots.snapshot] Snapshot folder ssl
>21-04-01 01:08:44 INFO (SyncWorker_3) [supervisor.snapshots.snapshot] Snapshot folder ssl done
>21-04-01 01:09:10 INFO (MainThread) [supervisor.snapshots] Creating full-snapshot with slug &lt;slug&gt; completed
