### ISSUE TITLE
stable.json get back to 2021.3.4 from time to time

### ISSUE THREAD

**Issue by mbo18** [home-assistant/supervisor#2800]
### Describe the issue you are experiencing

Using the `version` integration, I'm monitoring the last stable HA release in order to get a notification. Since the release
of 2021.4.0, the last release in stable.json get back to 2021.3.4 from time to time.

<img width="402" alt="version2" src="https://user-images.githubusercontent.com/12999535/114263093-d5e34780-99e3-11eb-80d7-7249d6ed5529.png">
<img width="1112" alt="stable" src="https://user-images.githubusercontent.com/12999535/114263097-dbd92880-99e3-11eb-87ff-a7033bd34d10.png">

### What is the used version of the Supervisor?

supervisor-2021.03.9

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

5.13

### What version of Home Assistant Core is installed?

core-2021.4.2

### Steps to reproduce the issue

1. Go to https://version.home-assistant.io/stable.json
2. Refresh until it goes back to 2021.3.4

### Anything in the Supervisor logs that might be useful for us?

```TXT
21-04-10 07:26:46 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
```

[version-home-assistant-io-har.zip](https://github.com/home-assistant/supervisor/files/6289474/version-home-assistant-io-har.zip)

https://version.home-assistant.io/cdn-cgi/trace
```TXT
fl=49f146
h=version.home-assistant.io
ip=v6
ts=1618042090.254
visit_scheme=https
uag=Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:87.0) Gecko/20100101 Firefox/87.0
colo=MRS
http=http/2
loc=FR
tls=TLSv1.3
sni=plaintext
warp=off
gateway=off
```

**Comment by MoritzBuetzer** [comment]
Same issue for me. As mentioned [here](https://twitter.com/wenzeldikt/status/1385493378062815237?s=20), my output from https://version.home-assistant.io/cdn-cgi/trace: 

```
fl=39f99
h=version.home-assistant.io
ip=2a02:1205:5054:2aa0:aca6:2568:53e0:2c84
ts=1619166140.216
visit_scheme=https
uag=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.72 Safari/537.36
colo=MXP
http=http/3
loc=CH
tls=TLSv1.3
sni=plaintext
warp=off
gateway=off
```

**Comment by andrecedik** [comment]
Had the same issue. Thanks for [responding so quickly](https://twitter.com/home_assistant/status/1385512009421053957). Here's my output:
```
fl=71f613
h=version.home-assistant.io
ip=185.68.78.241
ts=1619167104.38
visit_scheme=https
uag=Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.128 Safari/537.36
colo=FRA
http=http/2
loc=DE
tls=TLSv1.3
sni=plaintext
warp=off
gateway=off
```

**Comment by 0n3-70uch** [comment]
Hello, same issue here...
<img width="499" alt="Bildschirmfoto 2021-04-23 um 10 44 34" src="https://user-images.githubusercontent.com/6533600/115845282-f8805200-a420-11eb-911a-06480eaa8072.png">

**Comment by dikt1338** [comment]
![image](https://user-images.githubusercontent.com/40207389/115847879-a3920b00-a423-11eb-827e-9d69a3a13926.png)
fl=71f589
h=version.home-assistant.io
ip=not your business
ts=1619168672.316
visit_scheme=https
uag=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36
colo=FRA
http=http/2
loc=DE
tls=TLSv1.3
sni=plaintext
warp=off
gateway=off

**Comment by ludeeus** [comment]
Those of you that still see this, can use the "RELOAD" button on the "SYSTEM" tab to fix it

**Comment by 0n3-70uch** [comment]
> Those of you that still see this, can use the "RELOAD" button on the "SYSTEM" tab to fix it

Hi, no fix. Cleaning the cache does not work either.

**Comment by ludeeus** [comment]
And if you visit that URL you still see old values?

**Comment by dikt1338** [comment]
Works for mir. Did a couple of reloads and clicked "Update" but canceled the confirmation popup. Now it's fine

**Comment by 0n3-70uch** [comment]
> Works for me. Did a couple of reloads and clicked "Update" but canceled the confirmation popup. Now it's fine

Worked for me too. Thanks

**Comment by johnthomas00** [comment]
This url is switching back and forth between versions occasionally.  If you "watch" the url over a day or 2, you will see the changes
https://version.home-assistant.io/stable.json

**Comment by frenck** [comment]
@johnthomas00 The reason is unclear, but we now do know this problem originates from CloudFlare.

I've lowered the caching time, to prevent this from happening, however, if more "stale" caches occur, they can still be outdated. If not fixed by CloudFlare, we probably will face these issues for another month or so (from time to time, as that was the previous caching value).

**Comment by mbo18** [comment]
Solved here since yesterday

**Comment by johnthomas00** [comment]
Agreed, no problems since Apr 22, 7:32 PM Pacific Time.

**Comment by deftdawg** [comment]
Still happening...   Just now loading cached copy @ https://version.home-assistant.io/stable.json
```json
{
  "channel": "stable",
  "supervisor": "2021.03.9",
  "homeassistant": {
    "default": "2021.4.4",
    "qemux86": "2021.4.4",
    "qemux86-64": "2021.4.4",
    "qemuarm": "2021.4.4",
    "qemuarm-64": "2021.4.4",
    "generic-x86-64": "2021.4.4",
    "intel-nuc": "2021.4.4",
    "raspberrypi": "2021.4.4",
    "raspberrypi2": "2021.4.4",
    "raspberrypi3": "2021.4.4",
    "raspberrypi3-64": "2021.4.4",
    "raspberrypi4": "2021.4.4",
    "raspberrypi4-64": "2021.4.4",
    "tinker": "2021.4.4",
    "odroid-c2": "2021.4.4",
    "odroid-c4": "2021.4.4",
    "odroid-n2": "2021.4.4",
    "odroid-xu": "2021.4.4"
  },
  "hassos": {
    "ova": "5.13",
    "rpi": "5.13",
    "rpi0-w": "5.13",
    "rpi2": "5.13",
    "rpi3": "5.13",
    "rpi3-64": "5.13",
    "rpi4": "5.13",
    "rpi4-64": "5.13",
    "tinker": "5.13",
    "odroid-c2": "5.13",
    "odroid-c4": "5.13",
    "odroid-n2": "5.13",
    "odroid-xu4": "5.13",
    "generic-x86-64": "6.0.dev20210311",
    "intel-nuc": "5.13"
  },
  "ota": "https://github.com/home-assistant/operating-system/releases/download/{version}/hassos_{board}-{version}.raucb",
  "cli": "2021.03.1",
  "dns": "2021.01.0",
  "audio": "2021.02.1",
  "multicast": "2021.04.0",
  "observer": "2020.10.1",
  "image": {
    "core": "homeassistant/{machine}-homeassistant",
    "supervisor": "homeassistant/{arch}-hassio-supervisor",
    "cli": "homeassistant/{arch}-hassio-cli",
    "audio": "homeassistant/{arch}-hassio-audio",
    "dns": "homeassistant/{arch}-hassio-dns",
    "observer": "homeassistant/{arch}-hassio-observer",
    "multicast": "homeassistant/{arch}-hassio-multicast"
  }
}
```

Bypassing the caching @ https://version.home-assistant.io/stable.json?random=123456 
the versions are as expected: 
````json
{
  "channel": "stable",
  "supervisor": "2021.04.0",
  "homeassistant": {
    "default": "2021.4.6",
    "qemux86": "2021.4.6",
    "qemux86-64": "2021.4.6",
    "qemuarm": "2021.4.6",
    "qemuarm-64": "2021.4.6",
    "generic-x86-64": "2021.4.6",
    "intel-nuc": "2021.4.6",
    "raspberrypi": "2021.4.6",
    "raspberrypi2": "2021.4.6",
    "raspberrypi3": "2021.4.6",
    "raspberrypi3-64": "2021.4.6",
    "raspberrypi4": "2021.4.6",
    "raspberrypi4-64": "2021.4.6",
    "tinker": "2021.4.6",
    "odroid-c2": "2021.4.6",
    "odroid-c4": "2021.4.6",
    "odroid-n2": "2021.4.6",
    "odroid-xu": "2021.4.6"
  },
  "hassos": {
    "ova": "5.13",
    "rpi": "5.13",
    "rpi0-w": "5.13",
    "rpi2": "5.13",
    "rpi3": "5.13",
    "rpi3-64": "5.13",
    "rpi4": "5.13",
    "rpi4-64": "5.13",
    "tinker": "5.13",
    "odroid-c2": "5.13",
    "odroid-c4": "5.13",
    "odroid-n2": "5.13",
    "odroid-xu4": "5.13",
    "generic-x86-64": "6.0.dev20210311",
    "intel-nuc": "5.13"
  },
  "ota": "https://github.com/home-assistant/operating-system/releases/download/{version}/hassos_{board}-{version}.raucb",
  "cli": "2021.03.1",
  "dns": "2021.01.0",
  "audio": "2021.02.1",
  "multicast": "2021.04.0",
  "observer": "2020.10.1",
  "image": {
    "core": "homeassistant/{machine}-homeassistant",
    "supervisor": "homeassistant/{arch}-hassio-supervisor",
    "cli": "homeassistant/{arch}-hassio-cli",
    "audio": "homeassistant/{arch}-hassio-audio",
    "dns": "homeassistant/{arch}-hassio-dns",
    "observer": "homeassistant/{arch}-hassio-observer",
    "multicast": "homeassistant/{arch}-hassio-multicast"
  }
}
````

**Comment by frenck** [comment]
@deftdawg Could you check again?

**Comment by deftdawg** [comment]
Saw it once before you asked, but have not seen it since... 

The is the last one I caught; it was from the Chicacgo DC (ORD from the cluster @ 172.67.68.90)
```
* Connected to version.home-assistant.io (172.67.68.90) port 443 (#0)
< date: Wed, 28 Apr 2021 06:36:58 GMT
< content-type: application/json
< content-length: 1627
< set-cookie: __cfduid=d64ceecf2204f8866899164873572f2441619591818; expires=Fri, 28-May-21 06:36:58 GMT; path=/; domain=.home-assistant.io; HttpOnly; SameSite=Lax; Secure
< x-amz-id-2: TvrrwBKn0HWrFNUnIHzz8uEYEWpURBSkQ/XYkO6iUZvRRhF0hCAQK6Y+iC0H7eUlCh0rP2WozKc=
< x-amz-request-id: NM9ZP2XJJ7P0TR1S
< last-modified: Tue, 13 Apr 2021 02:06:26 GMT
< etag: "f16bd259cf42ea10877a23ec613f9ff8"
< cf-cache-status: HIT
< age: 1290790
< accept-ranges: bytes
< cf-request-id: 09b8cb04c200003fbab3b8a000000001
< expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< report-to: {"group":"cf-nel","max_age":604800,"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report?s=NoqVVaQ0MRVIhWmST%2BS6fFdtgrJdB7mggP6yEii2%2BivrFrtyg0%2BYv6FUGWI0ub9xEakrf6bvMP4gXQe9AcSbV%2FJZdOzgCIToe2Aohg%2BIFNQNZR7kFsGvn81k"}]}
< nel: {"report_to":"cf-nel","max_age":604800}
< server: cloudflare
< cf-ray: 646e47813c373fba-ORD
  "supervisor": "2021.03.9",
```

I'm guessing you republished and maybe killed the old cache, so it might be gone.  

If I see it again I'll try to capture the CF info (`curl -v https://version.home-assistant.io/stable.json  2>&1 | egrep -e "Connected to|supervisor|date|cf"`)

**Comment by robloh** [comment]
Maybe I'm misunderstanding how this works, but couldn't the UI/system simply ignore older versions than it's running? Then at least users and the system won't downgrade automatically

**Comment by deftdawg** [comment]
> Maybe I'm misunderstanding how this works, but couldn't the UI/system simply ignore older versions than it's running? Then at least users and the system won't downgrade automatically

HA's version numbers are not simple to compare unless the version format is set in stone...  Last year they switched from 0.88 to year.month.release; when simple string comparisons are done "2021.03.9" is greater than "2021.03.10" even though 10 is greater than 9 because the "1" in 10 comes before "9" when sorting.   

The system as it is now just checks is the remote version same as running version; if not then prompt to "upgrade".   Simple but effective provided caching behaves properly.  Also doesn't care what the version formatting is.

**Comment by ludeeus** [comment]
It does not do string compare, it uses <https://pypi.org/project/awesomeversion/> which correctly identifies that 10 > 9

**Comment by deftdawg** [comment]
Seems like the logic for `need_update` changed from `return self.version != self.latest_version` to `return self.version < self.latest_version`  in supervisor/init.py (https://github.com/home-assistant/supervisor/commit/80131ddfa87e646b5ce4d25c3810ab0745eb7dc6)...   

As @robloh said, guess we shouldn't be seeing it unless that hasn't been released or something else was missed.

**Comment by ludeeus** [comment]
It was not promoted to the stable channel until 2021.04.3
