### ISSUE TITLE
Unsupported after Supervisor update to 2022.6.2

### ISSUE THREAD

**Issue by to4ko** [home-assistant/supervisor#3715]
### Describe the issue you are experiencing

Getting unsupported state after suervisor updated to 2022.6.2

![image](https://user-images.githubusercontent.com/45161980/177525237-6033a87c-6a08-476a-b2d0-1b7dae8c1040.png)

Lean more lead to docker configuration - all recomendations are done

https://www.home-assistant.io/more-info/unsupported/docker_configuration

docker daemon config checked. record to grub added. reinstall from package done. host restarted.

no success at the moment

## System Health

version | core-2022.6.7
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.12
os_name | Linux
os_version | 5.18.0-0.bpo.1-amd64
arch | x86_64
timezone | Europe/Moscow

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4668
Installed Version | 1.25.5
Stage | running
Available Repositories | 1156
Downloaded Repositories | 24

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Debian GNU/Linux 11 (bullseye)
-- | --
update_channel | stable
supervisor_version | supervisor-2022.06.2
agent_version | 1.2.2
docker_version | 20.10.17
disk_total | 467.0 GB
disk_used | 48.3 GB
healthy | true
supported | failed to load: Unsupported
supervisor_api | ok
version_api | ok
installed_addons | Samba share (10.0.0), File editor (5.3.3), RPC Shutdown (2.2), Log Viewer (0.14.0), Home Assistant Google Drive Backup (0.108.2), IDE (2.2.0), Grafana (7.6.0), Mopidy (6e49c79), SSH & Web Terminal (11.0.1), MariaDB (2.4.0), Nginx Proxy Manager (0.12.0), AppDaemon (0.9.0), Check Home Assistant configuration (3.11.0), Frigate NVR (3.1), Portainer (2.14.0), Vaultwarden (Bitwarden) (0.17.0), chrony (2.4.0), Samba Backup (5.1.1), Terminal & SSH (9.4.0), ESPHome (dev) (dev), ESPHome (2022.6.2), Studio Code Server (5.1.2), Uptime Kuma (0.1.0), RTSPtoWeb - WebRTC (1.2.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 9
views | 22
mode | yaml

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | July 4, 2022 at 12:22
-- | --
current_recorder_run | July 6, 2022 at 12:49
estimated_db_size | 5594.80 MiB
database_engine | postgresql
database_version | 14.4

</details>

### What is the used version of the Supervisor?

supervisor-2022.06.2

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### What is the version of your installed operating system?

5.18.0-0.bpo.1-amd64

### What version of Home Assistant Core is installed?

core-2022.6.7

### Steps to reproduce the issue

not known

### Anything in the Supervisor logs that might be useful for us?

```txt
no errors in supervisor log
```

**Comment by Nanianmichaels** [comment]
What does it say when you click on "Learn More"?

In my case, it's a combination of extra docker containers and Docker configuration, which might have suffered along the way.

**Comment by to4ko** [comment]
In my case its docker configuration and all recomendations was followed with no success.

**Comment by Nanianmichaels** [comment]
Ah, I somehow skipped that line.

I can, however, confirm that my Docker json is correct according to the hep page, so this does seem to be a bug.

```
{
    "log-driver": "journald",
    "storage-driver": "overlay2"
}

```

**Comment by mdegat01** [comment]
What did you do after you followed the instructions in the "learn more" link? Did you restart the host or run any cli commands to get it to recheck? Supervisor has a schedule for refreshing its cache of info about the host but it's likely on the order of hours. Restarting the host is the quickest way to get it to read in your changes and re-run it's checks or I can look up the sequence of cli commands needed.

**Comment by to4ko** [comment]
> What did you do after you followed the instructions in the "learn more" link? Did you restart the host or run any cli commands to get it to recheck? Supervisor has a schedule for refreshing its cache of info about the host but it's likely on the order of hours. Restarting the host is the quickest way to get it to read in your changes and re-run it's checks or I can look up the sequence of cli commands needed.

as i stated in issue description - i've done all the steps advised on mentioned help and do restart host. not sure of the supervisor host check schedule can be the case here - 5 hours and statet still unsupported.

any supervisor reloads and restarts didn't help as well

**Comment by to4ko** [comment]
So looks like the issue is solved - with "sudo update-grub" - forgot to did it earlier this day. It is also missing in doc

https://www.home-assistant.io/more-info/unsupported/docker_configuration#the-solution

![image](https://user-images.githubusercontent.com/45161980/177577856-3f7a5b3e-c9fc-4cda-81f9-cf57f1ba310d.png)

**Comment by ronjtaylor** [comment]
Excuse my ignorance but I still have a problem supervisor won't start
I modified my /etc/default/grub to this but not sure of what I am doing
can you help me please
```
# If you change this file, run 'update-grub' afterwards to update
# /boot/grub/grub.cfg.
# For full documentation of the options in this file, see:
#   info -f grub -n 'Simple configuration'

GRUB_DEFAULT=0
GRUB_TIMEOUT_STYLE=hidden
GRUB_TIMEOUT=0
GRUB_DISTRIBUTOR=`lsb_release -i -s 2> /dev/null || echo Debian`
GRUB_CMDLINE_LINUX_DEFAULT=systemd.unified_cgroup_hierarchy=false
GRUB_CMDLINE_LINUX=""

# Uncomment to enable BadRAM filtering, modify to suit your needs
# This works with Linux (no patch required) and with any kernel that obtains
# the memory map information from GRUB (GNU Mach, kernel of FreeBSD ...)
#GRUB_BADRAM="0x01234567,0xfefefefe,0x89abcdef,0xefefefef"

# Uncomment to disable graphical terminal (grub-pc only)
#GRUB_TERMINAL=console

# The resolution used on graphical terminal
# note that you can use only modes which your graphic card supports via VBE
# you can see them in real GRUB with the command `vbeinfo'
#GRUB_GFXMODE=640x480

# Uncomment if you don't want GRUB to pass "root=UUID=xxx" parameter to Linux
#GRUB_DISABLE_LINUX_UUID=true

# Uncomment to disable generation of recovery mode menu entries
#GRUB_DISABLE_RECOVERY="true"

# Uncomment to get a beep at grub start
#GRUB_INIT_TUNE="480 440 1"
```

**Comment by Nanianmichaels** [comment]
I believe the issue is the lack of " before and after the text.

Try GRUB_CMDLINE_LINUX_DEFAULT="systemd.unified_cgroup_hierarchy=false"
