### ISSUE TITLE
Can't add network storage (mountin did not succeed)

### ISSUE THREAD

**Issue by rpdanjou** [home-assistant/supervisor#4359]
### The problem

I'm trying to connect to a netwokr share but this fails.
![image](https://github.com/home-assistant/core/assets/29733353/1602b93c-de7e-4ccb-9547-60cb93c250a5)

### What version of Home Assistant Core has the issue?

core-2023.6.0

### What type of installation are you running?

Home Assistant OS

### Anything in the logs that might be useful for us?

```txt
Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:125
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 2:46:04 PM (19 occurrences)
Last logged: 3:37:33 PM

Failed to to call /store -
Failed to to call /mounts - Mounting backup did not succeed. Check host logs for errors from mount or systemd unit mnt-data-supervisor-mounts-backup.mount for details.
Failed to to call /mounts - Mounting ha_backup did not succeed. Check host logs for errors from mount or systemd unit mnt-data-supervisor-mounts-ha_backup.mount for details.
Failed to to call /mounts - Mounting habackup did not succeed. Check host logs for errors from mount or systemd unit mnt-data-supervisor-mounts-habackup.mount for details.
Failed to to call /mounts - Mounting backups did not succeed. Check host logs for errors from mount or systemd unit mnt-data-supervisor-mounts-backups.mount for details.

Also checked logs trough terminal, same line but with date and time.
```

### Additional information

Tried various names for the network storage in HA, Remote hare and username, with and without special characters.
Also tried different passwords, with and without special characters, long and short (8chars).

Shot sure hot to perform "systemd unit mnt-data-supervisor-mounts-backups.mount". Have tried in terminal, but systemd does not seem to exits?

**Comment by jimmyz5150** [comment]
Hey just figured out
I had to take out the root drive directory for QNAP. After re reading this post got me thinking about directory structures and handling of the ip address.

**Comment by rpdanjou** [comment]
> I'm getting on HAos and using QNAP... Trying to use the "share" button setup Jun 08 19:30:38 homeassistant systemd[1]: Mounting Supervisor cifs mount: JZNAS_Share... Jun 08 19:30:38 homeassistant kernel: CIFS: Attempting to mount \192.168.x.xxx\JZ_Shared Jun 08 19:30:38 homeassistant mount[200941]: mount error(13): Permission denied Jun 08 19:30:38 homeassistant kernel: CIFS: Status code returned 0xc000006d STATUS_LOGON_FAILURE Jun 08 19:30:38 homeassistant kernel: CIFS: VFS: \192.168.x.xxx Send error in SessSetup = -13 Jun 08 19:30:38 homeassistant kernel: CIFS: VFS: cifs_mount failed w/return code = -13 Jun 08 19:30:38 homeassistant mount[200941]: Refer to the mount.cifs(8) manual page (e.g. man mount.cifs) and kernel log messages (dmesg) Jun 08 19:30:38 homeassistant systemd[1]: mnt-data-supervisor-mounts-JZNAS_Share.mount: Mount process exited, code=exited, status=32/n/a Jun 08 19:30:38 homeassistant systemd[1]: mnt-data-supervisor-mounts-JZNAS_Share.mount: Failed with result 'exit-code'. Jun 08 19:30:38 homeassistant systemd[1]: Failed to mount Supervisor cifs mount: JZNAS_Share. Jun 08 19:30:51 homeassistant systemd[1]: run-docker-runtime\x2drunc-moby-9f5a0265cf2e24e9883e9a2ec18ed9023534c9b0078e3310a85d1f61feae1482-runc.Ddx9Sh.mount: Deactivated successfully.
> 
> Is there any docs on this yet for setup? Thought it would be easy peasy lol

So, this is my host log:

Jun 08 14:00:32 homeassistant systemd[1]: Mounting Supervisor cifs mount: backups...
Jun 08 14:00:32 homeassistant kernel: CIFS: Attempting to mount \\192.168.2.4\HaBackup
Jun 08 14:00:32 homeassistant mount[24710]: mount error(95): Operation not supported
Jun 08 14:00:32 homeassistant mount[24710]: Refer to the mount.cifs(8) manual page (e.g. man mount.cifs) and kernel log messages (dmesg)
Jun 08 14:00:32 homeassistant kernel: CIFS: VFS: \\192.168.2.4 Dialect not supported by server. Consider  specifying vers=1.0 or vers=2.0 on mount for accessing older servers
Jun 08 14:00:32 homeassistant kernel: CIFS: VFS: cifs_mount failed w/return code = -95
Jun 08 14:00:32 homeassistant systemd[1]: mnt-data-supervisor-mounts-backups.mount: Mount process exited, code=exited, status=32/n/a
Jun 08 14:00:32 homeassistant systemd[1]: mnt-data-supervisor-mounts-backups.mount: Failed with result 'exit-code'.
Jun 08 14:00:32 homeassistant systemd[1]: Failed to mount Supervisor cifs mount: backups.

This is different from yous and seems like a compatibiliteit issue. Will check what setting I have on the NAS side (synology).

**Comment by rpdanjou** [comment]
So, this is my host log:

Jun 08 14:00:32 homeassistant systemd[1]: Mounting Supervisor cifs mount: backups...
Jun 08 14:00:32 homeassistant kernel: CIFS: Attempting to mount \\192.168.2.4\HaBackup
Jun 08 14:00:32 homeassistant mount[24710]: mount error(95): Operation not supported
Jun 08 14:00:32 homeassistant mount[24710]: Refer to the mount.cifs(8) manual page (e.g. man mount.cifs) and kernel log messages (dmesg)
Jun 08 14:00:32 homeassistant kernel: CIFS: VFS: \\192.168.2.4 Dialect not supported by server. Consider  specifying vers=1.0 or vers=2.0 on mount for accessing older servers
Jun 08 14:00:32 homeassistant kernel: CIFS: VFS: cifs_mount failed w/return code = -95
Jun 08 14:00:32 homeassistant systemd[1]: mnt-data-supervisor-mounts-backups.mount: Mount process exited, code=exited, status=32/n/a
Jun 08 14:00:32 homeassistant systemd[1]: mnt-data-supervisor-mounts-backups.mount: Failed with result 'exit-code'.
Jun 08 14:00:32 homeassistant systemd[1]: Failed to mount Supervisor cifs mount: backups.

This is different from yous and seems like a compatibiliteit issue. Will check what setting I have on the NAS side (synology).

**Comment by rpdanjou** [comment]
Fixed it!

Changed in Synology advanced SMB settings: Maximum SMB protocol to SMB3 instead of SMB2.

**Comment by kklicker777** [comment]
Hmmm.  Doesn't fix my problem, and I doubt kbloxsom either.  I think we both need to figure out what the "invalid argument" is and what the return code "-22" is.

**Comment by kklicker777** [comment]
Also, your fix would lead me to believe that only the SMB3 protocol is accepted?  Is this documented anywhere?  Because I just noticed that my Buffalo NAS drive with updated firmware only supports up to SMB2.  Unfortunately, I am left with more questions than answers.  Can a developer chime in here?

**Comment by aenigma-aenigma** [comment]
LINUX no longer supports SMB1 (not sure), I changed the settings on my Synology NAS to SMB 2-3

**Comment by kbloxsom** [comment]
I changed my router to a Netgear R6300 and was able to create network storage using CIFS. So happy camper!

**Comment by kklicker777** [comment]
Why do you have to change your router to get this to work?  So further research into this topic seems to suggest that if you specify the protocol version, i.e. vers=2.0 or vers=3.0 when creating the mount, you can bypass the error.  However, I see nowhere on the dialog that we are able to specify protocol version.  Can it be added?

**Comment by DJ-Anakin** [comment]
> LINUX no longer supports SMB1 (not sure), I changed the settings on my Synology NAS to SMB 2-3..and i Fix It!!!

This worked for me too! Thank you!

**Comment by rpdanjou** [comment]
> Hmmm. Doesn't fix my problem, and I doubt kbloxsom either. I think we both need to figure out what the "invalid argument" is and what the return code "-22" is.

This is more specifically about the -22: https://github.com/home-assistant/core/issues/94222
Maby you can find your solution there.

**Comment by nprez83** [comment]
> Why do you have to change your router to get this to work?  So further research into this topic seems to suggest that if you specify the protocol version, i.e. vers=2.0 or vers=3.0 when creating the mount, you can bypass the error.  However, I see nowhere on the dialog that we are able to specify protocol version.  Can it be added?

I would love to do this but I'm using an old external USB drive connected to my ASUS XT8 router. I don't see anywhere within the ASUS settings a place to change the SMB version. I can mount it into HA using the following shell command but can't get it to mount through the new UI. Running Hass OS with 2023.6.1 in a RPi4. It would be great if the UI added the capability to specify version.

```
mount -t cifs -o vers=1.0,username=user,password=pass //192.168.0.1/Reolink_doorbell /media/Reolink_doorbell
```

**Comment by kklicker777** [comment]
Yes!  Finally, someone who gets what I'm saying.  A simple Google search reveals this is the solution, yet we have crickets from the developers?  I don't see why the older versions of SMB can't be supported somewhere in the UI, most of our network drives are behind the firewall anyway.  Can't someone take this up and at least explain why it can't be done?

**Comment by miketarg** [comment]
I have the same issue, I also have a Asus router please can this be addressed asap??!
