### ISSUE TITLE
User configurable backup filename

### ISSUE THREAD

**Issue by jamesgeddes** [home-assistant/supervisor#4947]
### The problem

The backup service currently provides the user with the option to configure a `name`.

Counterintuitively, this does _not_ set the filename. Even when the `name` is set, the backup file is seemingly given a random string as a filename, such as,
- `969fad88.tar`
- `a1467f82.tar`
- `70344a3d.tar`

I assume it is random because it seems unlikely that these are hex dates;
- 969fad88 = 2050-01-29T05:30:48
- a1467f82 = 2055-09-28T13:45:38
- 70344a3d = 2029-08-29T21:44:29

According to [community members](https://community.home-assistant.io/t/how-do-i-name-the-backup-file/699449/2?u=jamesgeddes), it is not currently possible to set the file name. This limitation poses several challenges for users who rely on backup management systems or external services for storage and versioning.

### Use cases
- AWS S3 Integration: AWS S3, a commonly used cloud storage service, relies on consistent filenames for accurate versioning and retrieval of backup files. Enabling customizable filenames in Home Assistant would enhance compatibility with AWS S3 and similar services, ensuring seamless integration and reliable backup management.
- Backup System Compatibility: Various backup solutions, including rsync, BorgBackup, and Synology Hyper Backup, require filenames to adhere to specific formats for effective backup management and versioning. Allowing users to configure filenames in Home Assistant would facilitate seamless integration with these backup systems, enhancing overall backup efficiency and reliability.

### Proposed Solution
Allow users to customize backup filenames according to their preferences.

### What version of Home Assistant Core has the issue?

core-2024.2.5

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

Home Assistant Supervisor: Create a full backup.

### Example YAML snippet

```yaml
service: hassio.backup_full
metadata: {}
data:
  compressed: true
  location: nas
  name: habak
```

### Additional information

For context, my own daily backup process is as follows.
1. 0100: Output home assistant full backup to NAS
2. 0400: NAS backs up to AWS S3

With every backup getting a unique filename, it is not possible to use the AWS S3 built-in versioning capabilities. I will instead have to write a script that deletes the old backups from the NAS.

If I was able to set a consistent filename, new backups would overwrite the previous backup, which would ensure that
- my NAS does not fill up with old backup files.
- AWS S3 sees a new version of the same file.

I will gladly take this ticket if someone is able to,
- assign it to me.
- point me in the right direction!

---
_First reported by Tankegroda on 2020-04-03 in forum thread [Snapshot naming + Filename](https://community.home-assistant.io/t/snapshot-naming-filename/191348). Issue persists. I could not find a ticket here so apologies in advance if this is a duplicate._

**Comment by Alex-joomla** [comment]
This would be so great, if it gets fixed, but I'm not sure if it's really a bug :-/

**Comment by kinghat** [comment]
configurable backup filenames would be awesome but a good first step would be to have the filenames match the frontend. if i want to pull the backups i have no idea what they are other than their date.

**Comment by jamesgeddes** [comment]
@Alex-joomla
> I'm not sure if it's really a bug

I appreciate that this is perhaps on the grey line between feature request and a bug. If one were to view it from strict the perspective of the original feature specification to create backups, then if it is working as intended then it is this would be a feature request. If, however, we were to take user expectations into account, many users would expect that a `name` field should set a file name, which it does not. From that perspective, it is not working as an ordinary and reasonable person would expect, so it should be a bug. Either way, I am happy to be assigned to it so makes no odds to me.

@kinghat 
> a good first step would be to have the filenames match the frontend

If I have understood you correctly, that is what I am proposing here. The `name` field should set the name of the file. I am told that it sets the name of the backup, but I have not seen any reference to it elsewhere in the UI. It would also be good to be able to set use placeholders to substitute values in, including but not limited to dates, times, site name etc.

**Comment by chelming** [comment]
Still not "working" for me :)

**Comment by jamesgeddes** [comment]
Just because an issue is old does not mean that it is not important. Stalebot is a bad idea.

I have been waiting to be assigned to this so that I can fix it.

**Comment by chelming** [comment]
I'm still interested in being able to set backup names.

**Comment by kinghat** [comment]
> Just because an issue is old does not mean that it is not important. [Stalebot is a bad idea](https://drewdevault.com/2021/10/26/stalebot.html).
> 
> I have been waiting to be assigned to this so that I can fix it - or can I just crack on with it?

please crack on with it 😅

**Comment by chelming** [comment]
still want

**Comment by loocd** [comment]
Still want this

**Comment by jamesgeddes** [comment]
Stale bot is annoying...

I'll get to this asap.

**Comment by Shiroe93** [comment]
+1 for this feature/bug correction 
i set this up a couple of weeks ago and i assumed they would have the same name as in home assistant  out of curiosity i went to check everything was okay and found this

**Comment by LupinIII** [comment]
I came here, because I was trying to find a way to set the default backup name to something useful and was quite astonished that isn't possible. At least when downloading the backup file through the UI it gets the backup's name, but it being different in HA's filesystem is definitely more on the "bug" than the "feature request" side in my opinion.
Also for my initial reason the default name (if the name field is left empty when creating a manual backup for example) really should at least follow an ISO timestamp. Having files named "20_September_2024" isn't helpful.

**Comment by vobelic** [comment]
Also came in here looking for a solution for a native way to have the actual filename customized (or at least matching the UI one as stated previously).
This really should be working out of the box.

**Comment by jamesgeddes** [comment]
> should at least follow an ISO timestamp

ISO 8601 FTW!

Yes, when I get around to doing this (unless someone gets to it first!) I will include a timestamp option that provides an ISO8601 datetime. Then again, wouldn't the world be a much easier place if everybody could simply work in unix time 😂

**Comment by jamesgeddes** [comment]
Yes, stalebot, this issue does still exist and I do intend to get to it at some point.

**Comment by jamesgeddes** [comment]
If anyone else is able to get to this before me then that would be amazing. I intend get around to this as soon as I can but I am not sure when that will be.

**Comment by chelming** [comment]
pls no close

**Comment by csimonosian** [comment]
I would like this to be implemented too.

**Comment by jamesgeddes** [comment]
Problem still exists, dear old stalebot...

**Comment by bkjohnson** [comment]
That's correct as far as I know.

**Comment by Baxxy13** [comment]
If you do a manual backup and give the name e.g.:
`Backup Test partial`
Then this actually results with core-2025.2.0b10 in:
`Backup_Test_partial_2025-02-05_16.38_47769952.tar`

**Comment by agners** [comment]
Since Home Assistant Core 2025.1.0 the Backup is essentially handled by Home Assistant, which just forwards the request to Supervisor. And with the implementation in Home Assistant Core 2025.2.0 the filename will be set by Core as outlined by @Baxxy13 .

From Supervisor's perspective, the API has been extended to support filename with https://github.com/home-assistant/supervisor/pull/5567 and https://github.com/home-assistant/supervisor/pull/5568. So I consider this closed.

**Comment by jamesgeddes** [comment]
I'd arge that, since one still cannot specify the filename in full, this is not closed.

**Comment by csimonosian** [comment]
Yeah, this is a ticket categorisation and team workflow issue. It's been open almost a year, but now the responsiblity has moved to a different area. The ticket should move with the responsibility, not be closed and have to wait for a user to log the same thing again from scratch and have it assigned to a new area.
